import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teste Duosystem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main
            // className="h-screen"
            className="relative h-screen flex flex-col justify-center items-center"
          >
            <Navbar />
            <div className='pt-48 pb-20'>{children}</div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
