import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teste Duosystem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-pink-100"}>
        <Provider>
          <main
            className="relative flex flex-col justify-start items-center pt-28 pb-20"
          >
            <Navbar />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
